# Generated by Django 5.2.1 on 2025-10-20 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_alter_user_managers_user_is_admin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='qr_code',
        ),
    ]
